### ISSUE TITLE
romtables not treated as tables 

### ISSUE THREAD

**Issue by bikeNomad** [kikito/inspect.lua#11]
I'm trying to use inspect.lua with eLua, which adds the "romtable" type (LUA_TROTABLE). These are read-only tables that (for the purpose of inspection, anyway) work just like regular tables.

type(someromtable) returns "romtable" for these.

I've tried adding comparisions with 'romtable' in all the places I could find where the return value of type() was being compared with 'table', but had no success.

Would it be possible to add romtables to inspect.lua?

Thanks!

**Comment by kikito** [comment]
Since I have no way to test this myself, @bikeNomad has stopped responding, and no one else seems to need this feature, I am going to close this issue.

@bikeNomad, if you need this feature in the future, please reopen the issue (and schedule some time to make some tests, I can't do them myself).
