### ISSUE TITLE
Idea: long & nested array-like tables

### ISSUE THREAD

**Issue by premek** [kikito/inspect.lua#31]
Maybe array-like tables may be on one line if they are short (small amount of values or small sum of values' length?) and on separate lines if they are longer? E.g.

```
{ 
  {
    "assign", 
    { "id", "fun" },
    { "params", "a", "b", "c" }, 
    { 
      "block", 
      { "assign", 
        { "id", "A" }, 
        { "id", "2" } 
      }, 
      { "id", "4" }
    } 
  } 
}
``` 
instead of
```
{ { "assign", { "id", "fun" }, { "params", "a", "b", "c" }, { "block", { "assign", { "id", "A" }, { "id", "2" } }, { "id", "4" } } } }
```

**Comment by premek** [comment]
I think luaunit does something like that
https://github.com/bluebird75/luaunit/blob/master/luaunit.lua#L852

**Comment by kikito** [comment]
Hi there,

I am not opposed to something like this, but I don't think I would activate it by default. It could be done by adding an extra option in the `options` param. Or maybe making the `options.newline` option accept a function with some parameters to decide this kind of thing.

I gave a quick look at luaunit and it wasn't clear to me that the `keeponeline` variable worked as you say. It seems to me you must choose between "all in one line" (`keeponeline=true`) or "all elements in a new line, even the short ones" (`keeponeline=false`). There doesn't seem to be a way to "automatically deciding whether to keep things in one line or not depending on their length'.

What do you think? Would you consider making a pull request for this?

**Comment by premek** [comment]
I also had just a quick look to luaunit source, I'm not sure if the line I linked is the correct one, but luaunit works that way. This is some output form luaunit:
```
[...]
    {
        "knot",
        "dragged_outside",
        {"para", "He insisted that we hurried home to Savile Row"},
        {"divert", "as_fast_as_we_could"}
    },
    {"knot", "as_fast_as_we_could", "glue", {"para", "as fast as we could."}}
```
Two objects, both have strings and objects inside, first one is multiline, second one is one-line.

I may try to do a pull request if I find some time, thanks :)

**Comment by kikito** [comment]
Closing this for now, but feel free to send a PR if you want!
