### ISSUE TITLE
Add unrolling visited tables

### ISSUE THREAD

**Issue by iskolbin** [kikito/inspect.lua#32]
Hi there, awesome piece of soft!
I suggest to add an option to unroll already visited tables in the output. I.e.
```lua
local x = {1,2}
print( inspect( {x,x}, {unroll = true} )) -- should print {{1, 2}, {1, 2}}
```
I needed this functionality so I just commented out 3 lines:
```diff
241,242c241,242
<   elseif self:alreadyVisited(t) then
<     self:puts('<table ', self:getId(t), '>')
---
> --  elseif self:alreadyVisited(t) then
> --    self:puts('<table ', self:getId(t), '>')
246c246
< 		if self.tableAppearances[t] > 1 then self:puts('<', self:getId(t), '>') end
---
> --		if self.tableAppearances[t] > 1 then self:puts('<', self:getId(t), '>') end
```

**Comment by kikito** [comment]
I am afraid this won't be supported.

The main reason for not "unrolling" tables is table loops: if table A contains a reference to table B, and table B contains a reference to table A, if they are "unrolled", `inspect` would enter an infinite loop. The lines you erased are the only ones preventing this eventuality.
