### ISSUE TITLE
inspect does not render non printable values correctly

### ISSUE THREAD

**Issue by 4mig4** [kikito/inspect.lua#40]
How to replicate, please make a binary string for example : `\127\0\0\1`

```
require('inspect')
print(inspect('\127\0\0\1'))
```

**Comment by LoganDark** [comment]
I could open a pull request if this is required. inspect.lua could check to see if each character is outside the printable range (22 - 126 inclusive) and then replace it with an escape sequence...

**Comment by LoganDark** [comment]
Actually, hold on one minute.

https://github.com/kikito/inspect.lua/blob/b611db6bfa9c12ce35dd4972032fbbd2ad5ba965/spec/inspect_spec.lua#L41-L44

Test case...

**Comment by mpeterv** [comment]
So the problem is only with \127?

**Comment by LoganDark** [comment]
![image](https://user-images.githubusercontent.com/4723091/45187605-223fc880-b1e6-11e8-8ec6-d074dcc8811f.png)
Yes, as far as I can tell

**Comment by kikito** [comment]
I didn't notice this issue was open, apologies for that.

Some people consider the DEL character (char code 127) as "printable". I must have used some resource that did that, but TBH I didn't even think about it. I believe that it should be displayed. I will mark this as a bug.

**Comment by LoganDark** [comment]
> Some people consider the DEL character (char code 127) as "printable".

Control characters shouldn't be output verbatim, even if lua strings are completely binary safe, since inspect.lua's purpose is to output something to be read by a person, at least as far as I know.

**Comment by kikito** [comment]
Thanks for reporting this, I have released a fix that should properly escape DEL and released a new version of the luarock with it.
