### ISSUE TITLE
"Array"-style display option for tables

### ISSUE THREAD

**Issue by speeditor** [kikito/inspect.lua#43]
Firstly, I'd like to thank Kikito for producing this module. It's incredibly convenient for debugging, and it's literally invaluable to me in many cases (with metatables, or testing in restricted environments).

Currently the module outputs tables in this format:
```lua
{ "1", "2", [5] = "5", [6] = "once I pcall(A_FISH, ALIVE)" }
```
My suggestion is an option to display that table like this:
```lua
{ "1", "2", nil, nil, "5", "once I pcall(A_FISH, ALIVE)" }
```
Maybe `options.array` conditional?

Beyond the slight minification, the user could remove the brackets from the inspected table string. This produces a valid `unpack`ed "array" (an arguments list!). So in a roundabout way, this could be useful for test units etc. (anything that needs to turn a static table into an arguments list).

Here's an example of this working well in the Chrome browser console (I feel JS shouldn't allow this kind of behaviour, but that's another story ;D).
![image](https://user-images.githubusercontent.com/20615235/50298158-5d54c780-0476-11e9-93b8-10f2fc1155e9.png)

**Comment by speeditor** [comment]
@kikito thoughts? Pinging in case this library was considered feature complete in 2017. I do understand if this kinda feature is impossible, or needs too much refactoring (if any is welcome!).

**Comment by kikito** [comment]
Hi, I have decided not to include this.

In Lua, "arrays" (called **sequences**) are defined as "not having holes" in Programming In Lua (I can't find the exact part now). The way I interpret this is that first `nil`, and everything after is is **not part of the sequence**. The library reflects this opinion.

Please feel free to add that feature to your own fork. I will not be implementing this feature.
