### ISSUE TITLE
Looks strange with `inspect {{ x = 1 }}`

### ISSUE THREAD

**Issue by sumneko** [kikito/inspect.lua#55]
The result of `inspect {{ x = 1 }}` is

```lua
{ {
    x = 1
  } }
```

The indentation is not aligned, is this a special case or bug?

**Comment by borsuczyna** [comment]
You did table inside table, where's the problem

**Comment by sumneko** [comment]
> You did table inside table, where's the problem

It may be a common special case of this structure:

```lua
inspect { { x = 1 }, { x = 2 }, { x = 3 } }
```

Is it possible to keep their performance consistent?

However, I have no strong demand for this. If considering workload, cost performance or difficult ambiguity, I can accept the maintenance status.

**Comment by kikito** [comment]
You might not get exactly the output you want, but tweaking options.newline and options.indent might help.

See #58 for reference.
