### ISSUE TITLE
No option to print lua table in one line

### ISSUE THREAD

**Issue by Anshul0507** [kikito/inspect.lua#58]
Hi, Thanks for providing such a wonderful library.

I have created a custom plugin on kong in lua. I am using inspect library to log the whole request received from the user in the error log file. These logs are then sent to an elastic data source.
Every log line of my application contains the metadata like nginx worker's pid, connection serial number, file name. But as we know that in this case, the table params are printed in separate lines, so a new log line is generated for a new param.

For example, if my request is - {a=1, b=2,c=3}, then the request logged in the error file is -
{
    a=1,
    b=2,
    c=3
}

So I have no metadata information available for the params that are logged in new lines. This makes it difficult for me to get logs for the complete flow.

Is there a way I can get the complete request in one log line in this format - {a=1, b=2,c=3} ?

**Comment by kikito** [comment]
For your particular example you can use options.newline and options.indent:

```
print(require("inspect")({a=1, b=2}, {newline = " ", indent = ""}))

{ a = 1, b = 2 }
```

This will not scale for complex cases well but it might work for simple ones like yours.
