### ISSUE TITLE
How to remove `<table id>`?

### ISSUE THREAD

**Issue by adoyle-h** [kikito/inspect.lua#60]
I don't want to get `<table id>` and `<id>{}`, because it breaks the lua syntax highlights.

<img width="840" alt="CleanShot 2022-10-25 at 17 35 45@2x" src="https://user-images.githubusercontent.com/1998490/197739185-b31c4532-3ab6-4f57-866f-bd7275242208.png">

**Comment by kikito** [comment]
Thank you for reporting this.

The reason why it prints <1> and <table 1> when it encounters the same table more than once is to avoid infinite loops when it tries to parse recursive tables (tables than contain themselves). This is an integral part of inspect that I personally value more than being compatible with Lua syntax highlighting.

If this is very important for you, I see two possible avenues of action:
* you find a different library. Perhaps [Penligh's pl.pretty](https://stevedonovan.github.io/Penlight/api/libraries/pl.pretty.html) would fit your bill.
* you fork inspect and remove this feature in your fork

Have a nice day!

**Comment by adoyle-h** [comment]
Penligh's pl.pretty looks good to me. Thank you.
